// Code generated by tools/generate_unicode_identifiers.py; DO NOT EDIT.
// Source: Unicode 16.0.0 UCD; see ucd/README.md.

package unicodeident

// UnicodeVersion is the pinned Unicode Character Database version.
const UnicodeVersion = "16.0.0"

const (
	startOffset         = 8
	startCount          = 684
	continueOffset      = 5480
	continueCount       = 800
	combiningOffset     = 11880
	combiningCount      = 934
	decompositionOffset = 19352
	decompositionCount  = 5913
	compositionOffset   = 108237
	compositionCount    = 961
)
