#!/usr/bin/env python3
"""Rebuild PurePy's Unicode 16.0 name membership table using vendored inputs.

No network or Python Unicode database is used to generate the table. --check
compares generated bytes without writing them; --verify-cpython additionally
checks every source name against the development interpreter's literal decoder.
"""

from __future__ import annotations

import argparse
import codecs
import gzip
import hashlib
from pathlib import Path
import sys
import unicodedata

UNICODE_VERSION = "16.0.0"
BLOCK_SIZE = 32
ROOT = Path(__file__).resolve().parents[1]
PACKAGE = ROOT / "internal" / "unicodenames"
INPUTS = {
    "UnicodeData.txt": "ff58e5823bd095166564a006e47d111130813dcf8bf234ef79fa51a870edb48f",
    "NameAliases.txt": "9953f0fcebf5ea8091c5c581e4df0e43f20d2533c84ccca7987a9bb819a896a8",
}
# CPython 3.14's derived_name_range_names, with Hangul handled separately.
HEX_PREFIXES = {
    "CJK Ideograph": "CJK UNIFIED IDEOGRAPH-",
    "Tangut Ideograph": "TANGUT IDEOGRAPH-",
}
HANGUL_LEADS = "G GG N D DD R M B BB S SS  J JJ C K T P H".split(" ")
HANGUL_VOWELS = "A AE YA YAE EO E YEO YE O WA WAE OE YO U WEO WE WI YU EU YI I".split()
HANGUL_TAILS = [""] + "G GG GS N NJ NH D L LG LM LB LS LT LP LH M B BS S SS NG J C K T P H".split()


def read_input(name: str) -> str:
    data = gzip.decompress((PACKAGE / "ucd" / (name + ".gz")).read_bytes())
    if hashlib.sha256(data).hexdigest() != INPUTS[name]:
        raise ValueError(f"{name}: vendored Unicode {UNICODE_VERSION} SHA-256 mismatch")
    return data.decode("utf-8")


def source_names() -> tuple[dict[str, int], list[tuple[str, int, int]]]:
    names: dict[str, int] = {}
    ranges = []
    first = None
    for line in read_input("UnicodeData.txt").splitlines():
        cp, name, *_ = line.split(";")
        code = int(cp, 16)
        if name.endswith(", First>"):
            if first is not None:
                raise ValueError("nested Unicode ranges")
            first = (name[:-8], code)
        elif name.endswith(", Last>"):
            if first is None or first[0] != name[:-7]:
                raise ValueError("unpaired Unicode range")
            for stem, prefix in HEX_PREFIXES.items():
                if name.startswith("<" + stem):
                    ranges.append((prefix, first[1], code))
                    break
            first = None
        elif not name.startswith("<"):
            names[name] = code
    if first is not None:
        raise ValueError("unterminated Unicode range")
    for line in read_input("NameAliases.txt").splitlines():
        line = line.split("#", 1)[0].strip()
        if line:
            cp, name, _ = line.split(";")
            if name in names:
                raise ValueError(f"duplicate Unicode name: {name}")
            names[name] = int(cp, 16)
    if len(names) != 40490 or len(ranges) != 12:
        raise ValueError("unexpected Unicode 16.0 name or range count")
    for name in names:
        if not name or len(name) > 88 or any(c not in "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 -" for c in name):
            raise ValueError(f"unexpected Unicode name spelling: {name!r}")
    return names, ranges


def generate(names: dict[str, int], ranges: list[tuple[str, int, int]]) -> dict[str, bytes]:
    data = bytearray()
    offsets = []
    previous = ""
    for index, name in enumerate(sorted(names)):
        shared = 0
        if index % BLOCK_SIZE == 0:
            offsets.append(len(data))
        else:
            while shared < min(len(previous), len(name)) and previous[shared] == name[shared]:
                shared += 1
        suffix = name[shared:].encode("ascii")
        data.extend((shared, len(suffix)))
        data.extend(suffix)
        previous = name
    offsets.append(len(data))
    lines = [
        "// Code generated by tools/generate_unicode_names.py; DO NOT EDIT.",
        "// Source: Unicode 16.0.0 UnicodeData.txt and NameAliases.txt; see ucd/README.md.",
        "", "package unicodenames", "",
        '// UnicodeVersion is the pinned Unicode Character Database version.',
        f'const UnicodeVersion = "{UNICODE_VERSION}"', "",
        f"const maxNameLength = {max(map(len, names))}",
        f"const nameCount = {len(names)}", f"const blockSize = {BLOCK_SIZE}", "",
        "var blockOffsets = [...]uint32{",
    ]
    for offset in range(0, len(offsets), 12):
        lines.append("\t" + ", ".join(map(str, offsets[offset:offset + 12])) + ",")
    lines.extend(["}", "", "var hexRanges = [...]struct {", "\tprefix      string", "\tfirst, last uint32", "}{"])
    for prefix, first, last in ranges:
        lines.append(f'\t{{"{prefix}", 0x{first:X}, 0x{last:X}}},')
    lines.extend(["}", ""])
    return {"names.bin": bytes(data), "names_generated.go": "\n".join(lines).encode("ascii")}


def verify_cpython(names: dict[str, int], ranges: list[tuple[str, int, int]]) -> int:
    if sys.implementation.name != "cpython" or sys.version_info[:2] != (3, 14) or unicodedata.unidata_version != UNICODE_VERSION:
        raise ValueError("--verify-cpython requires CPython 3.14 with Unicode 16.0.0")
    all_names = dict(names)
    for prefix, first, last in ranges:
        all_names.update((f"{prefix}{code:X}", code) for code in range(first, last + 1))
    for li, lead in enumerate(HANGUL_LEADS):
        for vi, vowel in enumerate(HANGUL_VOWELS):
            for ti, tail in enumerate(HANGUL_TAILS):
                all_names[f"HANGUL SYLLABLE {lead}{vowel}{tail}"] = 0xAC00 + (li * 21 + vi) * 28 + ti
    for name, code in all_names.items():
        for spelling in (name, name.lower()):
            decoded = codecs.decode(("\\N{" + spelling + "}").encode("ascii"), "unicode_escape")
            if decoded != chr(code):
                raise ValueError(f"CPython disagrees with Unicode data: {spelling!r}")
    # A unicodedata.lookup result is not a sufficient escape oracle: named
    # sequences are accepted by lookup but deliberately excluded from literals.
    for name in ("KEYCAP NUMBER SIGN", "KEYCAP DIGIT ONE", "LATIN CAPITAL LETTER A WITH MACRON AND GRAVE"):
        if len(unicodedata.lookup(name)) < 2:
            raise ValueError(f"expected a named sequence: {name}")
        try:
            codecs.decode(("\\N{" + name + "}").encode("ascii"), "unicode_escape")
        except UnicodeDecodeError:
            continue
        raise ValueError(f"CPython accepted named sequence in an escape: {name}")
    invalid = {
        "", "LATIN  CAPITAL LETTER A", "LATIN-CAPITAL LETTER A",
        " LATIN CAPITAL LETTER A", "LATIN CAPITAL LETTER A ",
        "HANGUL SYLLABLE ", "HANGUL SYLLABLE G", "HANGUL SYLLABLE GAA",
        "CJK UNIFIED IDEOGRAPH-4E0", "CJK UNIFIED IDEOGRAPH-110000",
        "CJK COMPATIBILITY IDEOGRAPH-0F900", "KHITAN SMALL SCRIPT CHARACTER-018B00",
    }
    for prefix, first, last in ranges:
        invalid.update((f"{prefix}0{first:X}", f"{prefix}{first - 1:X}", f"{prefix}{last + 1:X}"))
    for name in invalid:
        for spelling in (name, name.lower()):
            try:
                codecs.decode(("\\N{" + spelling + "}").encode("ascii"), "unicode_escape")
            except UnicodeDecodeError:
                continue
            raise ValueError(f"CPython accepted a noncanonical or unassigned name: {spelling!r}")
    return len(all_names)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="check generated files without writing")
    parser.add_argument("--verify-cpython", action="store_true", help="compare all names with CPython 3.14 literal decoding")
    args = parser.parse_args()
    try:
        names, ranges = source_names()
        outputs = generate(names, ranges)
        for name, data in outputs.items():
            path = PACKAGE / name
            if args.check:
                if not path.exists() or path.read_bytes() != data:
                    raise ValueError(f"{path.relative_to(ROOT)} is stale; run tools/generate_unicode_names.py")
            else:
                path.write_bytes(data)
        if args.verify_cpython:
            count = verify_cpython(names, ranges)
            print(f"Unicode {UNICODE_VERSION}: {count} names and lowercase variants match CPython {sys.version.split()[0]}")
        print(f"Unicode {UNICODE_VERSION}: {len(names)} table names, {len(ranges)} algorithmic hex ranges; generated data {'verified' if args.check else 'written'}")
    except (OSError, ValueError, UnicodeError) as error:
        print(f"unicode names: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
