#!/usr/bin/env python3
"""Generate pinned Unicode 16.0 identifier and NFKC tables from vendored data.

Generation is offline and independent of the interpreter's Unicode database.
--check compares generated bytes; --verify-cpython compares XID properties and
the official normalization vectors with CPython 3.14's Unicode 16.0 database.
"""

from __future__ import annotations

import argparse
import gzip
import hashlib
from pathlib import Path
import struct
import sys
import unicodedata

UNICODE_VERSION = "16.0.0"
ROOT = Path(__file__).resolve().parents[1]
PACKAGE = ROOT / "internal" / "unicodeident"
INPUTS = {
    "UnicodeData.txt": "ff58e5823bd095166564a006e47d111130813dcf8bf234ef79fa51a870edb48f",
    "DerivedCoreProperties.txt": "39d35161f2954497f69e08bdb9e701493f476a3d30222de20028feda36c1dabd",
    "DerivedNormalizationProps.txt": "4d4c03892dea9146d674b686e495df2d55a28d071ac474041d73518f887abddc",
    "NormalizationTest.txt": "d811971453e7075e1ad56fb1b301eece5aa80757b81f6156e74a1bfb3ae5ceb1",
}


def read_input(name: str) -> str:
    package = ROOT / "internal" / "unicodenames" if name == "UnicodeData.txt" else PACKAGE
    data = gzip.decompress((package / "ucd" / (name + ".gz")).read_bytes())
    if hashlib.sha256(data).hexdigest() != INPUTS[name]:
        raise ValueError(f"{name}: vendored Unicode {UNICODE_VERSION} SHA-256 mismatch")
    return data.decode("utf-8")


def properties(text: str, wanted: str) -> set[int]:
    result = set()
    for line in text.splitlines():
        fields = [field.strip() for field in line.split("#", 1)[0].split(";")]
        if len(fields) < 2 or fields[1] != wanted:
            continue
        ends = fields[0].split("..")
        result.update(range(int(ends[0], 16), int(ends[-1], 16) + 1))
    return result


def ranges(values: set[int]) -> list[tuple[int, int]]:
    result = []
    for value in sorted(values):
        if result and result[-1][1] + 1 == value:
            result[-1] = (result[-1][0], value)
        else:
            result.append((value, value))
    return result


def source_tables() -> dict:
    core = read_input("DerivedCoreProperties.txt")
    excluded = properties(read_input("DerivedNormalizationProps.txt"), "Full_Composition_Exclusion")
    tables = {
        "start": properties(core, "XID_Start"),
        "continue": properties(core, "XID_Continue"),
        "combining": {}, "decomposition": {}, "composition": {},
    }
    for line in read_input("UnicodeData.txt").splitlines():
        fields = line.split(";")
        cp, cc = int(fields[0], 16), int(fields[3])
        if cc:
            tables["combining"][cp] = cc
        raw = fields[5].split()
        if not raw:
            continue
        compatibility = raw[0].startswith("<")
        if compatibility:
            raw = raw[1:]
        decomposition = tuple(int(value, 16) for value in raw)
        tables["decomposition"][cp] = "".join(map(chr, decomposition))
        if not compatibility and cp not in excluded:
            if len(decomposition) != 2:
                raise ValueError(f"unexpected composition for U+{cp:04X}")
            key = (decomposition[0] << 21) | decomposition[1]
            if key in tables["composition"]:
                raise ValueError(f"duplicate composition for U+{cp:04X}")
            tables["composition"][key] = cp
    if len(tables["start"]) != 141246 or len(tables["continue"]) != 144522:
        raise ValueError("unexpected Unicode 16.0 XID counts")
    return tables


def generate(tables: dict) -> dict[str, bytes]:
    data = bytearray(b"PYID16\0\0")
    sections = []
    for name in ("start", "continue"):
        rows = ranges(tables[name])
        sections.append((name, len(data), len(rows)))
        for first, last in rows:
            data.extend(struct.pack("<II", first, last))
    for name in ("combining", "decomposition", "composition"):
        rows = sorted(tables[name].items())
        sections.append((name, len(data), len(rows)))
        if name == "decomposition":
            offset = len(data) + len(rows) * 12
            strings = bytearray()
            for cp, value in rows:
                encoded = value.encode("utf-8")
                data.extend(struct.pack("<III", cp, offset + len(strings), len(encoded)))
                strings.extend(encoded)
            data.extend(strings)
        else:
            for key, value in rows:
                data.extend(struct.pack("<QI" if name == "composition" else "<II", key, value))
    lines = [
        "// Code generated by tools/generate_unicode_identifiers.py; DO NOT EDIT.",
        "// Source: Unicode 16.0.0 UCD; see ucd/README.md.",
        "", "package unicodeident", "",
        "// UnicodeVersion is the pinned Unicode Character Database version.",
        f'const UnicodeVersion = "{UNICODE_VERSION}"', "",
        "const (",
    ]
    # Constant alignment agrees with gofmt, keeping --check toolchain independent.
    constants = []
    for name, offset, count in sections:
        constants.extend([(name + "Offset", str(offset)), (name + "Count", str(count))])
    width = max(len(name) for name, _ in constants)
    for name, value in constants:
        lines.append(f"\t{name:<{width}} = {value}")
    lines.extend([")", ""])
    return {"identifiers.bin": bytes(data), "tables_generated.go": "\n".join(lines).encode("ascii")}


def verify_cpython(tables: dict) -> None:
    if sys.implementation.name != "cpython" or sys.version_info[:2] != (3, 14) or unicodedata.unidata_version != UNICODE_VERSION:
        raise ValueError("--verify-cpython requires CPython 3.14 with Unicode 16.0.0")
    for cp in range(0x110000):
        ch = chr(cp)
        if ch.isidentifier() != (cp in tables["start"] or ch == "_"):
            raise ValueError(f"CPython XID_Start mismatch at U+{cp:04X}")
        if ("A" + ch).isidentifier() != (cp in tables["continue"]):
            raise ValueError(f"CPython XID_Continue mismatch at U+{cp:04X}")
        if unicodedata.combining(ch) != tables["combining"].get(cp, 0):
            raise ValueError(f"CPython combining-class mismatch at U+{cp:04X}")
    count = 0
    for line in read_input("NormalizationTest.txt").splitlines():
        line = line.split("#", 1)[0].strip()
        if not line or line.startswith("@"):
            continue
        columns = ["".join(chr(int(cp, 16)) for cp in part.split()) for part in line.split(";")[:5]]
        for value in columns:
            if unicodedata.normalize("NFKC", value) != columns[3]:
                raise ValueError(f"CPython NFKC disagreement on {value!r}")
        count += 1
    print(f"Unicode {UNICODE_VERSION}: all scalar XID/combining properties and {count} normalization vectors match CPython {sys.version.split()[0]}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--verify-cpython", action="store_true")
    args = parser.parse_args()
    try:
        tables = source_tables()
        for name, data in generate(tables).items():
            path = PACKAGE / name
            if args.check:
                if not path.exists() or path.read_bytes() != data:
                    raise ValueError(f"{path.relative_to(ROOT)} is stale; run tools/generate_unicode_identifiers.py")
            else:
                path.write_bytes(data)
        if args.verify_cpython:
            verify_cpython(tables)
        print(f"Unicode {UNICODE_VERSION}: identifier and normalization tables {'verified' if args.check else 'written'}")
    except (OSError, ValueError, UnicodeError) as error:
        print(f"unicode identifiers: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
